### ISSUE TITLE
Script to run your own sensui

### ISSUE THREAD

**Issue by c-castillo** [uport-project/lambda-sensui#35]
Automate as much as possible. 
- Check you have your AWS credentials installed, 
- Check for a KMS key to encrypt/decrypt the secret
- Guidelines to configure AWS/CircleCI integration
- Delete/wipe the kms files (or remove from source control)

**Comment by KamesCG** [comment]
@c-castillo Bounty candidate?

**Comment by c-castillo** [comment]
@KamesCG Haven't thought about it, but the idea is great! 
If I unblock this writing documentation in the unclear/tricky parts, this fits as a great bounty candidate.

**Comment by ajunge** [comment]
Totally agreed . Let try to bounty it  @KamesCG
